# this allows the Baremetal Operator to boot and manage hosts for other clusters
# it also enables the operator on SNO clusters, where it is off by default
- name: Configure Baremetal Operator
  kubernetes.core.k8s:
    definition:
      apiVersion: metal3.io/v1alpha1
      kind: Provisioning
      metadata:
        name: provisioning-configuration
      spec:
        watchAllNamespaces: true
        provisioningNetwork: "Disabled"
    state: present

- name: Install MCE Operator
  block:
    - name: Install operator
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../common/roles/install_operator"
      vars:
        operator_name: multicluster-engine
        operator_namespace: multicluster-engine

    - name: Create MCE
      kubernetes.core.k8s:
        definition:
          apiVersion: multicluster.openshift.io/v1
          kind: MultiClusterEngine
          metadata:
            name: multiclusterengine
          spec: {}
        state: present
      register: create_mce

    - name: Pause for 15 seconds to let MCE settle
      ansible.builtin.pause:
        seconds: 15
      when: create_mce.changed

    - name: Wait for MCE to be deployed
      kubernetes.core.k8s_info:
        api_version: multicluster.openshift.io/v1
        kind: MultiClusterEngine
        name: multiclusterengine
      register: mce
      until: mce.resources[0].status.phase == "Available"
      retries: 60
      delay: 10

    # this config map is referenced by the AgentServiceConfig, these mirror settings are copied to the spoke clusters
    - name: Create mirror registry config map for spoke
      when: mirror_url is defined
      kubernetes.core.k8s:
        template: mirror-cm.yaml.j2
        state: present

    # see https://github.com/openshift/assisted-service/pull/2747
    - name: Configure Assisted Service to use mirror registry
      when: mirror_url is defined
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: assisted-service-config
            namespace: multicluster-engine
          data:
            PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.svc.ci.openshift.org,registry.redhat.io"
        state: present

    - name: Configure Assisted Service
      kubernetes.core.k8s:
        template: AgentServiceConfig.yaml.j2
        state: present
        wait: true
        wait_condition:
          type: DeploymentsHealthy
          status: "True"
        wait_timeout: 1200
  rescue:
    - name: Delete Assisted Service
      kubernetes.core.k8s:
        definition:
          apiVersion: agent-install.openshift.io/v1beta1
          kind: AgentServiceConfig
          metadata:
            name: agent
        state: absent
        wait: true
        wait_timeout: 1200
      ignore_errors: true # noqa ignore-errors

    - name: Delete MCE
      kubernetes.core.k8s:
        definition:
          apiVersion: multicluster.openshift.io/v1
          kind: MultiClusterEngine
          metadata:
            name: multiclusterengine
        state: absent
        wait: true
        wait_timeout: 1200
      ignore_errors: true # noqa ignore-errors

    - name: Delete namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: multicluster-engine
        state: absent
        wait: true
        wait_timeout: 1200

    - name: End playbook
      ansible.builtin.meta: end_play
