os_images:
  - openshiftVersion: "4.14"
    version: "4.14.34"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.16"
    version: "4.16.51"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.51/rhcos-4.16.51-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.18"
    version: "4.18.27"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.27/rhcos-4.18.27-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.20"
    version: "4.20.0"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.21"
    version: "4.21.0-ec.2"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.21.0-ec.2/rhcos-4.21.0-ec.2-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
asc_db_size: 10Gi
asc_fs_size: 50Gi
asc_im_size: 50Gi
