os_images:
  - openshiftVersion: "4.14"
    version: "4.14.34"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.16"
    version: "4.16.36"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.36/rhcos-4.16.36-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.18"
    version: "4.18.23"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.23/rhcos-4.18.23-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.19"
    version: "4.19.10"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.19/4.19.10/rhcos-4.19.10-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
  - openshiftVersion: "4.20"
    version: "4.20.0-rc.0"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.20.0-rc.0/rhcos-4.20.0-rc.0-x86_64-live-iso.x86_64.iso"
    cpuArchitecture: "x86_64"
asc_db_size: 10Gi
asc_fs_size: 50Gi
asc_im_size: 50Gi
