os_images:
  - openshiftVersion: "4.11"
    version: "4.11.2"
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.2/rhcos-4.11.2-x86_64-live.x86_64.iso"
    cpuArchitecture: "x86_64"
